### ISSUE TITLE
현재 ChatRoom 엔티티는 삭제되었지만 QChatRoom 이 삭제되지 않는 오류가 있습니다.

### ISSUE THREAD

**Issue by ca1af** [ca1af/sbug#19]
![image](https://user-images.githubusercontent.com/117057567/217257572-cd1a4ab1-137e-49b0-8371-b477e1cb9b70.png)

위 문제로 EntityManagerFactory 가 해당 Q클래스의 근원이 되는 Entity의 Path를 찾지 못하고 있습니다.

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: com/sparta/sbug/chatroom/entity/ChatRoom
```
에러 메시지 입니다. 
```java
Error creating bean with name 'entityManagerFactory' ...
com/sparta/sbug/chatroom/entity/ChatRoom
```
간략한 버전입니다. 해결책 찾고 있습니다.

**Comment by ca1af** [comment]
해결 방법은 스프링 부트 버전을 2.7.8 로 낮췄다가 다시 최신 버전으로 올리시면 됩니다.

**Comment by deok-beom** [comment]
JPAAnnotationProcessor라는 APT가 컴파일 시점에 작동하여 @Entity 어노테이션을 찾아 내용을 분석하고 Q클래스를 생성합니다.
이 과정으로 전에 컴파일 되어 생성된 클래스 파일 때문에 문제가 되고 있는 것으로 추정됩니다

클린 빌드(이전에 컴파일 된 파일들을 삭제하고 다시 빌드)하면 문제가 해결될 것으로 보입니다.
아래는 IntelliJ 기준으로 클린하는 방법입니다.

1. IntelliJ 상단의 Run Dialog 밑 Edit Configuration 선택, 혹은 왼쪽 위 메뉴에서 Run > Edit Configuration 선택
![image](https://user-images.githubusercontent.com/78391166/217409124-1febaa63-a3ce-4667-aa25-8a29157f13a6.png)

2. 더하기 모양 버튼(Add New Configuration)을 클릭하고  Gradle 선택
![image](https://user-images.githubusercontent.com/78391166/217409199-cdde517d-80bd-43f3-93f6-db7a39a6e9a8.png)

3. 아래와 같이 작업 입력 부분에 Clean을 입력하고 이름을 확인 후 저장
![image](https://user-images.githubusercontent.com/78391166/217409269-c78e3211-2ca5-4b35-89c5-7086292dd822.png)

4. 확인한 이름의 작업 실행(Run)
![image](https://user-images.githubusercontent.com/78391166/217409330-6710f6d5-aec2-4db5-bc9f-635f2534ca09.png)
