### ISSUE TITLE
포스트맨 간단하게 테스트 할 수 있는 방법 전달드립니다.

### ISSUE THREAD

**Issue by deok-beom** [ca1af/sbug#51]
환경 변수는 다음과 같이 설정합니다.
![image](https://user-images.githubusercontent.com/78391166/218457322-8ae07eaf-c4f3-474a-a860-e6eb0da8baba.png)

로그인하는 HTTP Request의 Test에 아래와 같이 입력해주세요
![image](https://user-images.githubusercontent.com/78391166/218457186-64f29cbd-4598-4ae8-896c-392abe4a229b.png)

```
const responseJson = pm.response.json();
pm.environment.set('atk', responseJson.atk);
pm.environment.set('rtk', responseJson.rtk);
```

값이 필요한 Request의 Header에 다음과 같이 입력해주시면 됩니다.
![image](https://user-images.githubusercontent.com/78391166/218457440-b03d4602-ae05-4f84-83da-3f4f8788216f.png)

```
Authorization {{atk}}
RTK {{rtk}}
```

**Comment by ca1af** [comment]
압도적 감사...
