### ISSUE TITLE
Schedule Controller 통합테스트(postman) 실패

### ISSUE THREAD

**Issue by youngfromnowhere** [ca1af/sbug#82]
![image](https://user-images.githubusercontent.com/55238763/220308755-5ffe8129-a10f-4262-b532-b727a3037baf.png)
Login Test 성공

![image](https://user-images.githubusercontent.com/55238763/220309220-d78d7ea6-37e9-459e-9550-e6ebf0c5a367.png)
그러나 Register Schedule 리퀘스트를 보내자 400 응답
detail에 Failed to read request라 되어 있어서 request 형식의 문제라 생각해
RequestDto가 날짜를 받는 형식을 바꿔봤으나 결과는 같습니다.

![image](https://user-images.githubusercontent.com/55238763/220309903-c25dea1c-4c98-4a88-b1c5-d7788c3cf575.png)
로그를 보면 AccessToken은 로그인때 받은대로 다시 전달이 된거 같습니다. 저 문구 전후로 select * from user 쿼리가 나갑니다

![image](https://user-images.githubusercontent.com/55238763/220310372-6e984edd-774a-44b4-9ffd-5a4ee5139aa2.png)
마지막 로그 메세지는 WebSocket 관련입니다.

![image](https://user-images.githubusercontent.com/55238763/220310861-6a41c97c-f7b4-45ea-aa36-54b7cd81be5a.png)

App 구동을 멈추고 gradle clean 후 다시 gradle compileJava (소스코드 컴파일) 했을 때 로그입니다.
컴파일은 잘 되는데 WebSocketSecurityConfig에서 deprecated API를 쓰고 있다는 메세지가 뜹니다.

혹시 웹소켓 쪽의 수정사항이 develop branch에 반영 안된 것이 있는걸까요?
웹소켓이 Schedule entity쪽이랑 전혀 관련이 없을것 같은데 로그 메세지에 웹소켓이 자꾸 언급됩니다.
(develop branch에서 merge 받은후 바로 feat/schedule 브랜치에서 작업했습니다.)

**Comment by deok-beom** [comment]
일단 웹 소켓 관련 로그는 현재 웹 소켓으로 연결되어 있거나 비정상적인 세션들의 정보를 보여주는 상태체크 메세지입니다.

코드를 확인하여 보니 아래와 같이 DTO의 어노테이션에 문제가 있었습니다.
![image](https://user-images.githubusercontent.com/78391166/220326868-389fbb6a-cc4e-488a-9084-5ebe7807e956.png)

POST의 `@RequestBody`에 사용되는 DTO는 `@NoArgsConstructor` 어노테이션을 사용하거나 기본 생성자를 만들어주어야 올바르게 작동됩니다. JSON으로 전달 받은 데이터는 역직렬화(문자열을 객체로 변환)를 거쳐 DTO에 값이 저장되게 되는데 그 과정 중 DTO를 기본 생성자로 먼저 생성하게 됩니다. 

> ++ DTO는 별도 Setter를 만들어주지 않아도 Java의 reflection(`java.lang.reflect`)이라는 API를 통해서 객체에 값을 주입 시켜줍니다. reflection은 힙 메모리에 생성된 데이터를 읽어 접근 제어자와 상관 없이 클래스, 메소드, 인터페이스 등을 생성하고 수정할 수 있도록 하는 기능입니다.
